name: Scrape listing of declared Conservative nominations for leadership candidates

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '*/5 * * * *'


jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Scrape
      run: |
        wget --no-cache "https://docs.google.com/spreadsheets/d/1PRufWhh2YAoxPUJEXeVaEOe7rcT1IINOXijeLI6o9Cc/export?format=csv" -O noms.csv
        wget --no-cache "https://docs.google.com/spreadsheets/d/1t1MaeGTmOvmOOkUL8TDDJwqTTc-N1wmRxPeRe0k3yjM/export?gid=0&format=csv" -O smarkets-endorsements.csv
        wget --no-cache "https://docs.google.com/spreadsheets/d/1t1MaeGTmOvmOOkUL8TDDJwqTTc-N1wmRxPeRe0k3yjM/export?gid=400125858&format=csv" -O smarkets-leaderboard.csv
        wget --no-cache "https://docs.google.com/spreadsheets/d/1t1MaeGTmOvmOOkUL8TDDJwqTTc-N1wmRxPeRe0k3yjM/export?gid=1659341012&format=csv" -O smarkets-candidates.csv

    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        gf_headline=$(head -3 noms.csv | tail -1 | tr -dc '[:alnum:],' | cut -d, -f2-4)
        sm_headline=$(tail -3 smarkets-leaderboard.csv | cut -d, -f3 | tr '\n' ',')
        git commit -m "${timestamp} GF: ${gf_headline} | Sm:   ${sm_headline}" || exit 0
        git pull --rebase
        git push
